const messageUtil = {
  // user message
  ALL_READY_EXIST: "All ready exist!",
  USER_CREATED: "User created!",
  USER_UPDATED: "User updated!",
  USER_DELETED: "User deleted!",
  USER_NOT_FOUND: "User not found!",
  serverError: "Server error!",
  INCORRECT_PASSWORD: "Incorrect password!",
  LOGIN_SUCCESS: "Login success!",
  OK: "OK",
  TOKEN_EMPTY: "Token is empty!",
  UNAUTHORIZED: "Unauthorized!",
  USER_DETAILS_FETCHED: "User details fetched successfully!",
  FORGOT_PASSWORD_EMAIL_SENT: "Forgot password email sent successfully!",
  PASSWORD_RESET_SUCCESS: "Password reset successfully!",
  FIRST_NAME_REQUIRED: "First name is required!",
  FIRST_NAME_TYPE: "First name must be a string!",
  LAST_NAME_REQUIRED: "Last name is required!",
  PASSWORD_REQUIRED: "Password is required!",
  PASSWORD_TYPE: "Password must be a string!",
  ROLE_REQUIRED: "Role is required!",
  LOGOUT_SUCCESS: "Logout success!",
  USER_REQUIRED: "User is required!",

  // project
  PROJECT_CREATED: "Project created!",
  PROJECT_UPDATED: "Project updated!",
  PROJECT_DELETED: "Project deleted!",
  PROJECT_NOT_FOUND: "Project not found!",
  PROJECT_NAME_REQUIRED: "Project name is required!",
  COMPANY_NAME_REQUIRED: "Company name is required!",
  COMPANY_NAME_TYPE: "Company name must be a string!",
  PROJECT_DESCRIPTION_REQUIRED: "Project description is required!",
  PROJECT_DESCRIPTION_TYPE: "Project description must be a string!",
  POINT_OF_CONTACT_REQUIRED: "Point of contact is required!",
  POINT_OF_CONTACT_TYPE: "Point of contact must be a string!",
  EMAIL_REQUIRED: "Email is required",
  EMAIL_TYPE: "Email type should be a string",
  DUE_DATE_REQUIRED: "Due date is required!",
  DUE_DATE_TYPE: "Due date must be a string!",
  PHONE_NUMBER_REQUIRED: "Phone number is required!",
  PHONE_NUMBER_TYPE: "Phone number must be a string!",
  ATTORNEY_REQUIRED: "Attorney is required!",
  ATTORNEY_TYPE: "Attorney must be a string!",
  CONFLICT_OF_INTEREST_REQUIRED: "Conflict of interest is required!",
  CONFLICT_OF_INTEREST_TYPE: "Conflict of interest must be a string!",
  EXAMINEE_REQUIRED: "Examinee is required!",
  EXAMINEE_TYPE: "Examinee must be a string!",
  FAILED_TO_CREATE_PROJECT: "Failed to create project!",
  FAILED_TO_FETCH_PROJECTS: "Failed to fetch projects!",
  FAILED_TO_UPDATE_PROJECT: "Failed to update project!",
  FAILED_TO_DELETE_PROJECT: "Failed to delete project!",
  PROJECT_FETCHED: "Project fetched successfully!",
  PROJECT_REQUIRED: "Project is required!",
  CLIENT_REQUIRED: "Client is required!",
  TASK_NAME_REQUIRED: "Task name is required!",
  TIME_REQUIRED: "Time is required!",
  STATUS_REQUIRED: "Status is required!",
  ASSIGNED_TO_REQUIRED: "Assigned to is required!",
  NOTES_REQUIRED: "Notes is required!",
  NOTES_TYPE: "Notes must be a string!",
  ISARCHIEVED_REQUIRED: "Isarchieved is required!",

  // task
  FAILED_TO_CREATE_TASK: "Failed to create task!",
  TASK_CREATED: "Task created!",
  TASK_UPDATED: "Task updated!",
  TASK_DELETED: "Task deleted!",
  TASK_NOT_FOUND: "Task not found!",
  FAILED_TO_FETCH_TASKS: "Failed to fetch tasks!",
  FAILED_TO_UPDATE_TASK: "Failed to update task!",
  FAILED_TO_DELETE_TASK: "Failed to delete task!",
  TASK_FETCHED: "Task fetched successfully!",
  TASK_REQUIRED: "Task is required!",
  FROM_REQUIRED: "From is required!",
  TO_REQUIRED: "To is required!",
  TASK_DESCRIPTION_REQUIRED: "Task description is required!",
  TASKS_EXIST: "Kindly remove task first",

  // invoice
  INVOICE_CREATED: "Invoice created!",
  INVOICE_UPDATED: "Invoice updated!",
  INVOICE_DELETED: "Invoice deleted!",
  INVOICE_NOT_FOUND: "Invoice not found!",
  FAILED_TO_CREATE_INVOICE: "Failed to create invoice!",
  FAILED_TO_FETCH_INVOICES: "Failed to fetch invoices!",
  FAILED_TO_UPDATE_INVOICE: "Failed to update invoice!",
  FAILED_TO_DELETE_INVOICE: "Failed to delete invoice!",
  INVOICE_FETCHED: "Invoice fetched successfully!",
  PROJECT_ALREADY_HAVE_INVOICE: "Project already have invoice!",
  INVOICE_EXIST: "Kindly remove invoice first",
  // schedule
  SCHEDULE_CREATED: "Schedule created!",
  SCHEDULE_UPDATED: "Schedule updated!",
  SCHEDULE_DELETED: "Schedule deleted!",
  SCHEDULE_NOT_FOUND: "Schedule not found!",
  FAILED_TO_CREATE_SCHEDULE: "Failed to create schedule!",
  FAILED_TO_FETCH_SCHEDULES: "Failed to fetch schedules!",
  FAILED_TO_UPDATE_SCHEDULE: "Failed to update schedule!",
  FAILED_TO_DELETE_SCHEDULE: "Failed to delete schedule!",
  SCHEDULE_FETCHED: "Schedule fetched successfully!",

  // date
  DATE_REQUIRED: "Date is required!",
  DATE_TYPE: "Date must be a string!",

  // taskName
  FAILED_TO_CREATE_TASKNAME: "Failed to create taskName!",
  TASKNAME_CREATED: "TaskName created!",
  TASKNAME_UPDATED: "TaskName updated!",
  TASKNAME_DELETED: "TaskName deleted!",
  TASKNAME_NOT_FOUND: "TaskName not found!",
  FAILED_TO_FETCH_TASKNAMES: "Failed to fetch taskNames!",
  FAILED_TO_UPDATE_TASKNAME: "Failed to update taskName!",
  FAILED_TO_DELETE_TASKNAME: "Failed to delete taskName!",
  TASKNAME_FETCHED: "TaskName fetched successfully!",

  // WorkedHours
  FAILED_TO_CREATE_WORKEDHOURS: "Failed to create workedHours!",
  WORKEDHOURS_CREATED: "WorkedHours created!",
  FAILED_TO_FETCH_WORKEDHOURS: "Failed to fetch workedHours!",
  WORKEDHOURS_FETCHED: "WorkedHours fetched successfully!",
  FAILED_TO_UPDATE_WORKEDHOURS: "Failed to update workedHours!",
  FAILED_TO_DELETE_WORKEDHOURS: "Failed to delete workedHours!",
  WORKEDHOURS_UPDATED: "WorkedHours updated!",
  WORKEDHOURS_DELETED: "WorkedHours deleted!",
  WORKED_HOURS_REQUIRED: "Worked hours is required!",
};

export default messageUtil;
